services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: my-server-container
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: my-client-container
    depends_on:
      - server
    stdin_open: true
    tty: true